#Spring Settings
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/team1_project
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 1000
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: limit
    redis:
      host: localhost
      port: 6379
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 446534610656-14r63n2kho9aggjkp8ebi1rgods392uj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/login/oauth2/callback/**
            scope:
              - email
              - profile

frontendUrl: http://localhost:3000
dataloader: 1

# jwt token
jwt:
  secretKey: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  accessTokenExpire: 8165431
  refreshTokenExpire: 564657
