spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 446534610656-14r63n2kho9aggjkp8ebi1rgods392uj.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/login/oauth2/callback/**
            scope:
              - email
              - profile

  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 1000
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: limit
    redis:
      host: localhost
      port: 6379

frontendUrl: http://localhost:8080

# jwt token
jwt:
  secretKey: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
  accessTokenExpire: 8165431
  refreshTokenExpire: 564657